import type { Assignment, Manager, Team } from './types'

export const lastUpdated = 'May 3, 2026 at 10:45 AM ET'

export const managers: Manager[] = [
  { id: 'manager-1', name: 'Avery Stone' },
  { id: 'manager-2', name: 'Maya Brooks' },
  { id: 'manager-3', name: 'Theo Park' },
  { id: 'manager-4', name: 'Nora Patel' },
  { id: 'manager-5', name: 'Leo Martinez' },
  { id: 'manager-6', name: 'Iris Chen' },
  { id: 'manager-7', name: 'Sam Rivera' },
  { id: 'manager-8', name: 'Quinn Morgan' },
  { id: 'manager-9', name: 'Elena Rossi' },
  { id: 'manager-10', name: 'Jules Carter' },
]

export const teams: Team[] = [
  { id: 'team-brazil', name: 'Brazil', goals: 12, status: 'active' },
  { id: 'team-japan', name: 'Japan', goals: 7, status: 'eliminated' },
  { id: 'team-morocco', name: 'Morocco', goals: 8, status: 'active' },
  { id: 'team-canada', name: 'Canada', goals: 3, status: 'eliminated' },
  { id: 'team-france', name: 'France', goals: 14, status: 'champion' },
  { id: 'team-ghana', name: 'Ghana', goals: 5, status: 'eliminated' },
  { id: 'team-uruguay', name: 'Uruguay', goals: 6, status: 'active' },
  { id: 'team-south-korea', name: 'South Korea', goals: 4, status: 'eliminated' },
  { id: 'team-argentina', name: 'Argentina', goals: 13, status: 'active' },
  { id: 'team-switzerland', name: 'Switzerland', goals: 6, status: 'eliminated' },
  { id: 'team-senegal', name: 'Senegal', goals: 7, status: 'active' },
  { id: 'team-saudi-arabia', name: 'Saudi Arabia', goals: 2, status: 'eliminated' },
  { id: 'team-england', name: 'England', goals: 11, status: 'active' },
  { id: 'team-mexico', name: 'Mexico', goals: 5, status: 'eliminated' },
  { id: 'team-croatia', name: 'Croatia', goals: 7, status: 'active' },
  { id: 'team-qatar', name: 'Qatar', goals: 1, status: 'eliminated' },
  { id: 'team-spain', name: 'Spain', goals: 10, status: 'active' },
  { id: 'team-cameroon', name: 'Cameroon', goals: 4, status: 'eliminated' },
  { id: 'team-united-states', name: 'United States', goals: 6, status: 'active' },
  { id: 'team-wales', name: 'Wales', goals: 2, status: 'eliminated' },
  { id: 'team-portugal', name: 'Portugal', goals: 9, status: 'active' },
  { id: 'team-ecuador', name: 'Ecuador', goals: 5, status: 'eliminated' },
  { id: 'team-serbia', name: 'Serbia', goals: 4, status: 'eliminated' },
  { id: 'team-australia', name: 'Australia', goals: 6, status: 'active' },
  { id: 'team-netherlands', name: 'Netherlands', goals: 8, status: 'active' },
  { id: 'team-poland', name: 'Poland', goals: 4, status: 'eliminated' },
  { id: 'team-tunisia', name: 'Tunisia', goals: 3, status: 'eliminated' },
  { id: 'team-costa-rica', name: 'Costa Rica', goals: 2, status: 'eliminated' },
  { id: 'team-germany', name: 'Germany', goals: 7, status: 'eliminated' },
  { id: 'team-denmark', name: 'Denmark', goals: 3, status: 'eliminated' },
  { id: 'team-iran', name: 'Iran', goals: 4, status: 'eliminated' },
  { id: 'team-belgium', name: 'Belgium', goals: 5, status: 'active' },
  { id: 'team-italy', name: 'Italy', goals: 6, status: 'eliminated' },
  { id: 'team-chile', name: 'Chile', goals: 4, status: 'eliminated' },
  { id: 'team-nigeria', name: 'Nigeria', goals: 5, status: 'active' },
  { id: 'team-new-zealand', name: 'New Zealand', goals: 1, status: 'eliminated' },
  { id: 'team-colombia', name: 'Colombia', goals: 5, status: 'active' },
  { id: 'team-peru', name: 'Peru', goals: 3, status: 'eliminated' },
  { id: 'team-egypt', name: 'Egypt', goals: 4, status: 'eliminated' },
  { id: 'team-scotland', name: 'Scotland', goals: 2, status: 'eliminated' },
  { id: 'team-norway', name: 'Norway', goals: 9, status: 'active' },
  { id: 'team-sweden', name: 'Sweden', goals: 8, status: 'active' },
  { id: 'team-ireland', name: 'Ireland', goals: 5, status: 'eliminated' },
  { id: 'team-greece', name: 'Greece', goals: 4, status: 'eliminated' },
  { id: 'team-turkey', name: 'Turkey', goals: 7, status: 'active' },
  { id: 'team-ukraine', name: 'Ukraine', goals: 6, status: 'eliminated' },
  { id: 'team-paraguay', name: 'Paraguay', goals: 3, status: 'eliminated' },
  { id: 'team-ivory-coast', name: 'Ivory Coast', goals: 5, status: 'active' },
]

export const assignments: Assignment[] = [
  { managerId: 'manager-1', teamId: 'team-brazil' },
  { managerId: 'manager-1', teamId: 'team-japan' },
  { managerId: 'manager-1', teamId: 'team-morocco' },
  { managerId: 'manager-1', teamId: 'team-canada' },
  { managerId: 'manager-2', teamId: 'team-france' },
  { managerId: 'manager-2', teamId: 'team-ghana' },
  { managerId: 'manager-2', teamId: 'team-uruguay' },
  { managerId: 'manager-2', teamId: 'team-south-korea' },
  { managerId: 'manager-3', teamId: 'team-argentina' },
  { managerId: 'manager-3', teamId: 'team-switzerland' },
  { managerId: 'manager-3', teamId: 'team-senegal' },
  { managerId: 'manager-3', teamId: 'team-saudi-arabia' },
  { managerId: 'manager-4', teamId: 'team-england' },
  { managerId: 'manager-4', teamId: 'team-mexico' },
  { managerId: 'manager-4', teamId: 'team-croatia' },
  { managerId: 'manager-4', teamId: 'team-qatar' },
  { managerId: 'manager-5', teamId: 'team-spain' },
  { managerId: 'manager-5', teamId: 'team-cameroon' },
  { managerId: 'manager-5', teamId: 'team-united-states' },
  { managerId: 'manager-5', teamId: 'team-wales' },
  { managerId: 'manager-6', teamId: 'team-portugal' },
  { managerId: 'manager-6', teamId: 'team-ecuador' },
  { managerId: 'manager-6', teamId: 'team-serbia' },
  { managerId: 'manager-6', teamId: 'team-australia' },
  { managerId: 'manager-7', teamId: 'team-netherlands' },
  { managerId: 'manager-7', teamId: 'team-poland' },
  { managerId: 'manager-7', teamId: 'team-tunisia' },
  { managerId: 'manager-7', teamId: 'team-costa-rica' },
  { managerId: 'manager-8', teamId: 'team-germany' },
  { managerId: 'manager-8', teamId: 'team-denmark' },
  { managerId: 'manager-8', teamId: 'team-iran' },
  { managerId: 'manager-8', teamId: 'team-belgium' },
  { managerId: 'manager-9', teamId: 'team-italy' },
  { managerId: 'manager-9', teamId: 'team-chile' },
  { managerId: 'manager-9', teamId: 'team-nigeria' },
  { managerId: 'manager-9', teamId: 'team-new-zealand' },
  { managerId: 'manager-10', teamId: 'team-colombia' },
  { managerId: 'manager-10', teamId: 'team-peru' },
  { managerId: 'manager-10', teamId: 'team-egypt' },
  { managerId: 'manager-10', teamId: 'team-scotland' },
]
